Controllers/HomeController.cs
using Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gelir_Gider_Yonetim_Sistemi.Models;
namespace Gelir_Gider_Yonetim_Sistemi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            var bugun = DateTime.Today;
            var ayinIlkGunu = new DateTime(bugun.Year, bugun.Month, 1); 
            var ayinSonrakiIlkGunu = ayinIlkGunu.AddMonths(1);
            var yilBaslangici = new DateTime(bugun.Year, 1, 1); 
            var yilSonu = yilBaslangici.AddYears(1);

            var gelirTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList
                .Where(k => k.KayitTur == "Gelir")
                .Sum(k => k.Tutar);

            var giderTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList
                .Where(k => k.KayitTur == "Gider")
                .Sum(k => k.Tutar);


            var gunlukGelirTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList
                .Where(k => k.KayitTur == "Gelir" && k.KayitTarih.Date == bugun)
                .Sum(k => k.Tutar);

            var gunlukGiderTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList
                .Where(k => k.KayitTur == "Gider" && k.KayitTarih.Date == bugun)
                .Sum(k => k.Tutar);

            var aylikGelirTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList.Where(k => k.KayitTur == "Gelir" && k.KayitTarih >= ayinIlkGunu && k.KayitTarih < ayinSonrakiIlkGunu)
    .Sum(k => k.Tutar);

            var aylikGiderTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList
   .Where(k => k.KayitTur == "Gider" && k.KayitTarih >= ayinIlkGunu && k.KayitTarih < ayinSonrakiIlkGunu)
   .Sum(k => k.Tutar);

            var yillikGelirTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList
    .Where(k => k.KayitTur == "Gelir" && k.KayitTarih >= yilBaslangici && k.KayitTarih < yilSonu)
    .Sum(k => k.Tutar);
            var yillikGiderTutarlariToplami = Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri.KayitGelirGider.KayitList
    .Where(k => k.KayitTur == "Gider" && k.KayitTarih >= yilBaslangici && k.KayitTarih < yilSonu)
    .Sum(k => k.Tutar);

            ViewBag.YillikGelirTutarlariToplami = yillikGelirTutarlariToplami;
            ViewBag.YillikGiderTutarlariToplami = yillikGiderTutarlariToplami;

            ViewBag.AylikGelirTutarlariToplami = aylikGelirTutarlariToplami;
            ViewBag.AylikGiderTutarlariToplami = aylikGiderTutarlariToplami;

            ViewBag.GunlukGelirTutarlariToplami = gunlukGelirTutarlariToplami;
            ViewBag.GunlukGiderTutarlariToplami = gunlukGiderTutarlariToplami;

            ViewBag.GelirTutarlariToplami = gelirTutarlariToplami;
            ViewBag.GiderTutarlariToplami = giderTutarlariToplami;
            return View();
        }
    }
}

Controllers/KayitController.cs
using Gelir_Gider_Yonetim_Sistemi.Models;
using Gelir_Gider_Yonetim_Sistemi.Models.GelirGiderVeri;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gelir_Gider_Yonetim_Sistemi.Controllers
{
    public class KayitController : Controller
    {
   
        public ActionResult KayitSil(int id)
        {
            var kayit = Models.GelirGiderVeri.KayitGelirGider.KayitList.FirstOrDefault(k => k.Id == id);

            if (kayit != null)
            {
                Models.GelirGiderVeri.KayitGelirGider.KayitList.Remove(kayit);
            }

            return RedirectToAction("KayitListele");
        }
        public ActionResult KayitListele()
        {
            var kayitList = Models.GelirGiderVeri.KayitGelirGider.KayitList.OrderByDescending(t=>t.KayitTarih).ToList();
            return View(kayitList);
        }

        public ActionResult KayitEkle()
        {
            return View(new Models.KayitGelirGider());
        }

        [HttpPost]
        public ActionResult KayitEkle(Models.KayitGelirGider yeniKayit) 
        {
            if (ModelState.IsValid)
            {
                var eklenecekKayit = new Models.KayitGelirGider
                {
                    KayitTur = yeniKayit.KayitTur,
                    KayitTarih = yeniKayit.KayitTarih,
                    KayitAciklama = yeniKayit.KayitAciklama,
                    Tutar = yeniKayit.Tutar
                };
                Models.GelirGiderVeri.KayitGelirGider.KayitList.Add(eklenecekKayit);

                return RedirectToAction("KayitListele");
            }
            return View(yeniKayit);
        }
        public ActionResult KayitEdit(int id)
        {
            var kayit = Models.GelirGiderVeri.KayitGelirGider.KayitList.FirstOrDefault(k => k.Id == id);
            if (kayit == null)
            {
                return HttpNotFound();
            }
            return View("KayitListele", kayit);
        }


        [HttpPost]
        public ActionResult KayitEdit(Models.KayitGelirGider kayit)
        {
            if (ModelState.IsValid)
            {
                var existingKayit = Models.GelirGiderVeri.KayitGelirGider.KayitList.FirstOrDefault(k => k.Id == kayit.Id);
                if (existingKayit != null)
                {
                    existingKayit.KayitTur = kayit.KayitTur;
                    existingKayit.KayitTarih = kayit.KayitTarih;
                    existingKayit.KayitAciklama = kayit.KayitAciklama;
                    existingKayit.Tutar = kayit.Tutar;
                }
                return RedirectToAction("KayitListele");
            }
            return View(kayit);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<div class="container text-center m-2">
    <div class="row align-items-center">
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 ">
            <div style="min-height: 350px">
                <canvas id="myChart1" height="300"></canvas>
                <script>
                    const yillikGelirTutarlariToplami = @ViewBag.YillikGelirTutarlariToplami ;
                    const yillikGiderTutarlariToplami = @ViewBag.YillikGiderTutarlariToplami ;

                    const ctx1 = document.getElementById('myChart1').getContext('2d');
                    const myChart1 = new Chart(ctx1, {
                        type: 'bar',
                        data: {
                            labels: ['Gelir', 'Gider'],
                            datasets: [{
                                label: ['Yılık Gelir Gider'],
                                data: [yillikGelirTutarlariToplami, yillikGiderTutarlariToplami],
                                backgroundColor: [
                                    'rgba(26,54,99,0.7)',
                                    'rgba(244,130,32,0.7)'
                                ],
                                borderColor: [
                                    'rgb(26,54,99)',
                                    'rgb(244,130,32)'
                                ],
                                borderWidth: 1
                            }]
                        },
                        options: {
                            scales: {
                                y: {
                                    beginAtZero: true

                                }
                            }
                        }
                    });
                </script>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <div style="min-height: 350px;">
                <canvas id="myChart3" height="300"></canvas>
                <script>
             const aylikGelirTutarlariToplami = @ViewBag.AylikGelirTutarlariToplami;
             const aylikGiderTutarlariToplami = @ViewBag.AylikGiderTutarlariToplami;
             const ctx3 = document.getElementById('myChart3').getContext('2d');

             new Chart(ctx3, {
                 type: 'bar',
                 data: {
                     labels: ['Gelir', 'Gider'],

                     datasets: [{
                         label: 'Aylik Gelir Gider',
                         data: [aylikGelirTutarlariToplami, aylikGiderTutarlariToplami],
                         backgroundColor: [
                             'rgba(26,54,99,0.7)',
                             'rgba(244,130,32,0.7)'
                         ],
                         borderColor: [
                             'rgb(26,54,99)',
                             'rgb(244,130,32)'
                         ],
                         borderWidth: 1
                     }]
                 },
                 options: {
                     scales: {
                         y: {
                             beginAtZero: true
                         }
                     }
                 }
             });
                </script>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <div style="min-height: 350px;">
                <canvas id="myChart2" height="300"></canvas>
                <script>
                    const gunlukGelirTutarlariToplami = @ViewBag.GunlukGelirTutarlariToplami;
                    const gunlukGiderTutarlariToplami = @ViewBag.GunlukGiderTutarlariToplami;
                    const ctx2 = document.getElementById('myChart2').getContext('2d');

                    new Chart(ctx2, {
                        type: 'bar',
                        data: {
                            labels: ['Gelir', 'Gider'],
                            datasets: [{
                                label: 'Günlük Gelir Gider',
                                data: [gunlukGelirTutarlariToplami, gunlukGiderTutarlariToplami],
                                backgroundColor: [
                                    'rgba(26,54,99,0.7)',
                                    'rgba(244,130,32,0.7)'
                                ],
                                borderColor: [
                                    'rgb(26,54,99)',
                                    'rgb(244,130,32)'
                                ],

                                borderWidth: 1
                            }]
                        },
                        options: {
                            scales: {
                                y: {
                                    beginAtZero: true
                                }
                            }
                        }
                    });
                </script>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <div style="min-height: 350px;">
                <canvas id="myChart4" height="300"></canvas>
                <script>
                    const gelirTutarlariToplami = @ViewBag.GelirTutarlariToplami;
                    const giderTutarlariToplami = @ViewBag.GiderTutarlariToplami;
                    const ctx4 = document.getElementById('myChart4').getContext('2d');
                    new Chart(ctx4, {
                        type: 'pie',
                        data: {
                            labels: ['Gelir', 'Gider'],

                            datasets: [{
                                label: 'Total Gelir Gider',
                                data: [gelirTutarlariToplami, giderTutarlariToplami],

                                backgroundColor: [
                                    'rgba(26,54,99,0.7)',
                                    'rgba(244,130,32,0.7)'
                                ],
                                borderColor: [
                                    'rgb(54, 162, 235)',
                                    '#F48220'
                                ],

                                borderWidth: 1
                            }]
                        },
                        options: {
                            scales: {
                                y: {
                                    beginAtZero: true
                                }
                            }
                        }
                    });
                </script>
                <p class="fw-bold" style="color: #1a3663;font-size:18px">Total Gelir Gider Grafiği</p>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            
                <div style="min-height: 350px;">
                    <canvas id="myChart5" height="300"></canvas>
                    <script>
                        const taylikGelirTutarlariToplami = @ViewBag.AylikGelirTutarlariToplami;
                        const taylikGiderTutarlariToplami = @ViewBag.AylikGiderTutarlariToplami;
                        const ctx5 = document.getElementById('myChart5').getContext('2d');
                        new Chart(ctx5, {
                            type: 'pie',
                            data: {
                                labels: ['Gelir', 'Gider'],

                                datasets: [{
                                    label: 'Aylik Gelir Gider',
                                    data: [taylikGelirTutarlariToplami, taylikGiderTutarlariToplami],
                                    backgroundColor: [
                                        'rgba(26,54,99,0.7)',
                                        'rgba(244,130,32,0.7)'
                                    ],
                                    borderColor: [
                                        'rgb(26,54,99)',
                                        'rgb(244,130,32)'
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true
                                    }
                                }
                            }
                        });
                    </script>
                    <p class="fw-bold" style="color: #1a3663;font-size:18px">Aylık Gelir Gider Grafiği</p>
                </div>
           
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
            @Html.ActionLink("Gelir Gider Kayıt İşlemleri İçin Tıklayınız", "KayitListele", "Kayit", new { area = "" }, new { @class = "btn btn-kayit px-3 py-3 d-flex align-items-center", style = "font-size:26px;min-height:300px" })
        </div>
    </div>
</div>